### ISSUE TITLE
请问可以发一下数据库吗？

### ISSUE THREAD

**Issue by Jey-xu** [sunshine-peng/houseLeaseSystem#22]
你好啊，请问可以发一下项目数据库吗？（感谢感谢）

**Comment by sunshine-peng** [comment]
旧电脑坏了，数据库文件全部丢失了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunshine-peng/houseLeaseSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 晚上8:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [sunshine-peng/houseLeaseSystem] 请问可以发一下数据库吗？ (Issue #22)





 
Closed #22.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
